#pragma once
enum OBJ { OBJ_PLAYER, OBJ_MONSTER, OBJ_BULLET, OBJ_ITEM, OBJ_MON_BULLET, OBJ_PLAYER_SHIELD,OBJ_END };
enum DIR { DIR_LEFT, DIR_RIGHT, DIR_TOP, DIR_BOTTOM, DIR_END };
enum TYPE { PLAYER,NOMAL, BOOM, BOSS, SHIELD ,PORTION, ATSPEED, QUANTITY};
enum BOSSPATTERN { MACHINEGUN, SHOTGUN , GUIDED };